import 'package:xml/xml.dart';

import 'feed_dates.dart';
import 'feed_duration.dart';
import 'parsed_feed.dart';
import 'plain_text.dart';

const _itunes = 'http://www.itunes.com/dtds/podcast-1.0.dtd';
const _media = 'http://search.yahoo.com/mrss/';
const _content = 'http://purl.org/rss/1.0/modules/content/';
const _dc = 'http://purl.org/dc/elements/1.1/';

/// Parses RSS 2.0 with the iTunes, Media RSS, Dublin Core and content
/// namespaces.
///
/// Throws [FeedFormatException] only when there is no feed to read. Every
/// lesser problem — an item with no audio, a date in an invented format —
/// becomes a warning, because a feed with one broken episode out of four
/// hundred is still a feed worth subscribing to.
ParsedFeed parseFeed(String xml) {
  final XmlDocument document;
  try {
    document = XmlDocument.parse(xml);
  } on XmlException catch (e) {
    throw FeedFormatException('not well-formed XML: ${e.message}');
  }

  final root = document.rootElement;
  if (root.localName == 'feed') {
    throw const FeedFormatException(
      'Atom feeds are not supported; v1 reads RSS 2.0 (§12)',
    );
  }

  final channel = _child(root, 'channel') ??
      (root.localName == 'channel' ? root : null);
  if (channel == null) {
    throw const FeedFormatException('no <channel> element');
  }

  final warnings = <String>[];
  final items = <ParsedItem>[];

  final rawItems = channel.childElements
      .where((e) => e.localName == 'item' && e.namespacePrefix == null)
      .toList(growable: false);

  for (var position = 0; position < rawItems.length; position++) {
    final item = _parseItem(rawItems[position], position, warnings);
    if (item != null) items.add(item);
  }

  if (items.isEmpty && rawItems.isNotEmpty) {
    warnings.add('every one of the ${rawItems.length} items was unusable');
  }

  return ParsedFeed(
    title: plainText(_text(channel, 'title')),
    author: plainText(_text(channel, 'author', ns: _itunes, prefix: 'itunes') ??
        _text(channel, 'creator', ns: _dc, prefix: 'dc') ??
        _text(channel, 'managingEditor')),
    description: _trimmedOrNull(_text(channel, 'description') ??
        _text(channel, 'summary', ns: _itunes, prefix: 'itunes')),
    artworkUrl: _artwork(channel),
    items: items,
    warnings: warnings,
  );
}

ParsedItem? _parseItem(XmlElement item, int position, List<String> warnings) {
  final enclosure = _enclosureUrl(item);
  if (enclosure == null) {
    // No audio, no episode. Feeds carry trailers, blog cross-posts and the
    // occasional empty placeholder; none of them are playable.
    warnings.add(
      'item #$position (${_text(item, 'title') ?? 'untitled'}) has no '
      'playable enclosure',
    );
    return null;
  }

  final rawDate = _text(item, 'pubDate') ??
      _text(item, 'date', ns: _dc, prefix: 'dc') ??
      _text(item, 'pubdate');
  final publishedAt = parseFeedDate(rawDate);
  if (publishedAt == null && rawDate != null && rawDate.trim().isNotEmpty) {
    warnings.add('item #$position has an unreadable date: "${rawDate.trim()}"');
  }

  return ParsedItem(
    title: plainText(_text(item, 'title')) ??
        plainText(_text(item, 'title', ns: _itunes, prefix: 'itunes')) ??
        _titleFromUrl(enclosure),
    enclosureUrl: enclosure,
    feedPosition: position,
    guid: _trimmedOrNull(_text(item, 'guid')),
    publishedAt: publishedAt,
    duration:
        parseFeedDuration(_text(item, 'duration', ns: _itunes, prefix: 'itunes')),
    description: _trimmedOrNull(
      _text(item, 'encoded', ns: _content, prefix: 'content') ??
          _text(item, 'description') ??
          _text(item, 'summary', ns: _itunes, prefix: 'itunes'),
    ),
    artworkUrl: _artwork(item),
  );
}

/// `<enclosure url>` is the specified place. `<media:content url>` is where
/// feeds generated by a video-first CMS put it instead.
Uri? _enclosureUrl(XmlElement item) {
  for (final e in item.childElements) {
    if (e.localName == 'enclosure') {
      final url = _uri(e.getAttribute('url'));
      if (url != null) return url;
    }
  }
  for (final e in item.childElements) {
    if (e.localName == 'content' &&
        (e.namespaceUri == _media || e.namespacePrefix == 'media')) {
      final url = _uri(e.getAttribute('url'));
      if (url != null) return url;
    }
  }
  return null;
}

Uri? _artwork(XmlElement parent) {
  final itunesImage = _element(parent, 'image', ns: _itunes, prefix: 'itunes');
  final href = _uri(itunesImage?.getAttribute('href'));
  if (href != null) return href;

  final thumb = _element(parent, 'thumbnail', ns: _media, prefix: 'media');
  final thumbUrl = _uri(thumb?.getAttribute('url'));
  if (thumbUrl != null) return thumbUrl;

  // RSS's own <image><url>…</url></image>, which only appears on the channel.
  final rssImage = _child(parent, 'image');
  return _uri(rssImage == null ? null : _text(rssImage, 'url'));
}

/// A last resort for an episode with no title at all: the audio file's name is
/// at least something the user can recognise, and is better than four hundred
/// rows all reading "Untitled".
String _titleFromUrl(Uri url) {
  final name = url.pathSegments.isEmpty ? '' : url.pathSegments.last;
  final withoutExtension =
      name.contains('.') ? name.substring(0, name.lastIndexOf('.')) : name;
  return withoutExtension.isEmpty ? 'Untitled episode' : withoutExtension;
}

/// Matches on local name and prefix rather than resolved namespace URI.
///
/// Feeds routinely use `itunes:` without ever declaring it, which leaves
/// [XmlElement.namespaceUri] null while the prefix survives intact. Insisting
/// on a resolved URI would silently drop durations from a large minority of
/// real feeds; accepting either is what the probe of `package:xml` showed to
/// be necessary.
XmlElement? _element(XmlElement parent, String localName,
    {String? ns, String? prefix}) {
  for (final e in parent.childElements) {
    if (e.localName != localName) continue;
    if (ns == null) {
      if (e.namespacePrefix == null) return e;
    } else if (e.namespaceUri == ns || e.namespacePrefix == prefix) {
      return e;
    }
  }
  return null;
}

XmlElement? _child(XmlElement parent, String localName) =>
    _element(parent, localName);

String? _text(XmlElement parent, String localName, {String? ns, String? prefix}) =>
    _element(parent, localName, ns: ns, prefix: prefix)?.innerText;

String? _trimmedOrNull(String? text) {
  final trimmed = text?.trim();
  return trimmed == null || trimmed.isEmpty ? null : trimmed;
}

/// Rejects anything without a scheme, and repairs the two malformations that
/// are common enough to be worth repairing: protocol-relative URLs, and URLs
/// with unescaped spaces.
Uri? _uri(String? raw) {
  var text = _trimmedOrNull(raw);
  if (text == null) return null;
  if (text.startsWith('//')) text = 'https:$text';
  text = text.replaceAll(' ', '%20');
  final parsed = Uri.tryParse(text);
  if (parsed == null || !parsed.hasScheme || parsed.host.isEmpty) return null;
  return parsed;
}
